// User Login
const SET_AUTH = 'SET_AUTH';
const DELETE_AUTH = 'DELETE_AUTH';
const CREATE_USER = 'CREATE_USER';

// Categories & Products
const SET_CATEGORIES = 'SET_CATEGORIES';
const SET_PRODUCTS = 'SET_PRODUCTS';

// Orders
const SET_ORDERS = 'SET_ORDERS';
const CREATE_ORDER = 'CREATE_ORDER';
const UPDATE_ORDER = 'UPDATE_ORDER';
const DELETE_ORDER = 'DELETE_ORDER';

// Cart / Line Items (cart is a colletion of line items)
const SET_CART = 'SET_CART';
const ADD_LINEITEM = 'ADD_LINEITEM';
const UPDATE_LINEITEM = 'UPDATE_LINEITEM';
const DELETE_LINEITEM = 'DELETE_LINEITEM';

// Brands
const SET_BRANDS = 'SET_BRANDS';

export {
  SET_AUTH,
  DELETE_AUTH,
  CREATE_USER,
  SET_BRANDS,
  SET_CATEGORIES,
  SET_PRODUCTS,
  SET_ORDERS,
  CREATE_ORDER,
  UPDATE_ORDER,
  DELETE_ORDER,
  SET_CART,
  ADD_LINEITEM,
  UPDATE_LINEITEM,
  DELETE_LINEITEM,
};
